### ISSUE TITLE
必修授業の学習における禁止事項の画面で落ちる

### ISSUE THREAD

**Issue by KanbaraRyusei** [ItoSeiy/Selenium-WebDriver-ZPrep#36]
## おそらくチェックボックスが正しく押されていないため発生している
![image](https://github.com/ItoSeiy/Selenium-WebDriver-ZPrep/assets/89116978/356aa199-ab71-4936-8849-d9ec58f1a916)

## 多分この辺が関係ある
![image](https://github.com/ItoSeiy/Selenium-WebDriver-ZPrep/assets/89116978/b4906da8-ffda-4f07-bd14-86d3f5ce83db)
![image](https://github.com/ItoSeiy/Selenium-WebDriver-ZPrep/assets/89116978/f456c83f-70af-404d-86f8-8770b8c64eda)

## ここ修正すれば行けそう？
https://github.com/ItoSeiy/Selenium-WebDriver-ZPrep/blob/45ca3beab016c2d90b26589e0e0f8d73f61324d0/zprep/main.py#L426C5-L426C5

# 修正お願いします（迫真）

**Comment by ItoSeiy** [comment]
@KanbaraRyusei 
的を得てて合っているんだけど別ブランチのコードで既に修正済みなんよね、、、、

https://github.com/ItoSeiy/Selenium-WebDriver-ZPrep/blob/feature/zprep_v2/zprep/libs/selenium.py#L257

いまはビルド周りで苦戦してて止まってる
